/* Hi Fi PDF Tool Kit — Tools Configuration */
const TOOL_CATEGORIES = [
  { id: 'all', name: 'All Tools', icon: 'fas fa-th-large' },
  { id: 'organize', name: 'Organize', icon: 'fas fa-layer-group' },
  { id: 'optimize', name: 'Optimize', icon: 'fas fa-tachometer-alt' },
  { id: 'convert-to', name: 'Convert To PDF', icon: 'fas fa-file-import' },
  { id: 'convert-from', name: 'Convert From', icon: 'fas fa-file-export' },
  { id: 'edit', name: 'Edit PDF', icon: 'fas fa-edit' },
  { id: 'security', name: 'Security', icon: 'fas fa-shield-alt' },
  { id: 'ai', name: 'AI Tools', icon: 'fas fa-robot' },
  { id: 'viral', name: 'Viral Tools', icon: 'fas fa-fire' },
  { id: 'extras', name: 'Extras', icon: 'fas fa-puzzle-piece' }
];

const ALL_TOOLS = [
  // === ORGANIZE PDF ===
  { id:'merge-pdf', name:'Merge PDF', icon:'fas fa-object-group', iconBg:'icon-bg-purple', category:'organize', badge:'hot',
    desc:'Combine multiple PDF files into one document instantly.',
    keywords:'merge pdf, combine pdf, join pdf files, merge pdf online free',
    metaDesc:'Merge PDF files online for free. Combine multiple PDFs into one document in seconds. Fast, secure, no signup required — Hi Fi PDF Tool Kit.',
    intro:'Easily merge multiple PDF files into a single document. Upload your files, arrange the order, and download your merged PDF in seconds.',
    steps:['Upload multiple PDF files','Drag to rearrange the order','Click Merge PDF','Download your combined file'],
    benefits:[{icon:'⚡',title:'Lightning Fast',desc:'Merge files in seconds'},{icon:'🔒',title:'100% Secure',desc:'Files auto-delete after processing'},{icon:'📱',title:'Works Everywhere',desc:'Use on any device'},{icon:'♾️',title:'No Limits',desc:'Merge unlimited files'}],
    faq:[{q:'How to merge PDF files?',a:'Upload your PDFs, arrange them in order, and click Merge. Your combined PDF downloads instantly.'},{q:'Is it free to merge PDFs?',a:'Yes, completely free with no signup or watermarks.'},{q:'Is my data safe?',a:'Yes, all processing happens in your browser. Files are never uploaded to any server.'}],
    related:['split-pdf','compress-pdf','rotate-pdf','remove-pages'] },

  { id:'split-pdf', name:'Split PDF', icon:'fas fa-cut', iconBg:'icon-bg-purple', category:'organize',
    desc:'Split a PDF into multiple separate documents.',
    keywords:'split pdf, separate pdf pages, divide pdf',
    metaDesc:'Split PDF files online for free. Separate PDF pages into individual documents. Fast & secure — Hi Fi PDF Tool Kit.',
    intro:'Split your PDF into multiple files. Extract specific pages or split every page into a separate document.',
    steps:['Upload your PDF file','Choose split method (by pages, ranges, or all)','Click Split PDF','Download split files'],
    benefits:[{icon:'✂️',title:'Precise Splitting',desc:'Split by page ranges'},{icon:'⚡',title:'Instant Results',desc:'Get files in seconds'},{icon:'🔒',title:'Private & Secure',desc:'Browser-based processing'},{icon:'📦',title:'Batch Download',desc:'Download all at once'}],
    faq:[{q:'How to split a PDF?',a:'Upload your PDF, select pages to extract, and click Split.'},{q:'Can I split specific pages?',a:'Yes, enter page numbers or ranges like 1-3, 5, 7-10.'}],
    related:['merge-pdf','extract-pages','remove-pages','compress-pdf'] },

  { id:'remove-pages', name:'Remove Pages', icon:'fas fa-minus-circle', iconBg:'icon-bg-purple', category:'organize',
    desc:'Remove unwanted pages from your PDF.',
    keywords:'remove pdf pages, delete pages from pdf',
    metaDesc:'Remove pages from PDF online free. Delete unwanted pages from your PDF document easily — Hi Fi PDF Tool Kit.',
    intro:'Select and remove specific pages from your PDF document with just a few clicks.',
    steps:['Upload your PDF','Select pages to remove','Click Remove Pages','Download updated PDF'],
    benefits:[{icon:'🎯',title:'Precise Control',desc:'Select exact pages'},{icon:'⚡',title:'Fast Processing',desc:'Instant results'},{icon:'🔒',title:'Secure',desc:'No server upload'},{icon:'💯',title:'Quality Preserved',desc:'No quality loss'}],
    faq:[{q:'How to delete pages from PDF?',a:'Upload your PDF, click on pages to remove them, then download.'}],
    related:['extract-pages','split-pdf','rearrange-pages','merge-pdf'] },

  { id:'extract-pages', name:'Extract Pages', icon:'fas fa-file-download', iconBg:'icon-bg-purple', category:'organize',
    desc:'Extract specific pages from a PDF file.',
    keywords:'extract pdf pages, get pages from pdf',
    metaDesc:'Extract pages from PDF online free. Pull specific pages from your PDF document — Hi Fi PDF Tool Kit.',
    intro:'Extract specific pages from your PDF and save them as a new document.',
    steps:['Upload your PDF','Select pages to extract','Click Extract','Download new PDF'],
    benefits:[{icon:'📄',title:'Page Selection',desc:'Pick any pages'},{icon:'⚡',title:'Fast',desc:'Instant extraction'},{icon:'🔒',title:'Secure',desc:'Client-side processing'},{icon:'✨',title:'Original Quality',desc:'No degradation'}],
    faq:[{q:'How to extract pages?',a:'Upload PDF, select the pages you want, click Extract.'}],
    related:['split-pdf','remove-pages','merge-pdf','rearrange-pages'] },

  { id:'rearrange-pages', name:'Rearrange Pages', icon:'fas fa-random', iconBg:'icon-bg-purple', category:'organize',
    desc:'Reorder pages in your PDF by dragging and dropping.',
    keywords:'rearrange pdf pages, reorder pdf, sort pdf pages',
    metaDesc:'Rearrange PDF pages online free. Drag and drop to reorder pages — Hi Fi PDF Tool Kit.',
    intro:'Drag and drop to rearrange pages in your PDF. Change the page order exactly how you want it.',
    steps:['Upload your PDF','Drag pages to reorder','Click Save','Download reordered PDF'],
    benefits:[{icon:'🖱️',title:'Drag & Drop',desc:'Intuitive reordering'},{icon:'👁️',title:'Visual Preview',desc:'See pages before saving'},{icon:'⚡',title:'Instant',desc:'Quick processing'},{icon:'🔒',title:'Secure',desc:'Browser-only processing'}],
    faq:[{q:'How to rearrange PDF pages?',a:'Upload your PDF, drag pages into the desired order, then save.'}],
    related:['remove-pages','extract-pages','merge-pdf','rotate-pdf'] },

  { id:'scan-to-pdf', name:'Scan to PDF', icon:'fas fa-camera', iconBg:'icon-bg-purple', category:'organize',
    desc:'Convert scanned images to PDF documents.',
    keywords:'scan to pdf, image scan pdf, photo to pdf',
    metaDesc:'Scan to PDF online free. Convert camera photos and scanned images to PDF — Hi Fi PDF Tool Kit.',
    intro:'Convert your scanned images or camera photos into clean PDF documents.',
    steps:['Upload scanned images','Arrange page order','Adjust settings','Download PDF'],
    benefits:[{icon:'📷',title:'Camera Ready',desc:'Use phone camera'},{icon:'📄',title:'Clean Output',desc:'Professional PDFs'},{icon:'⚡',title:'Fast Convert',desc:'Instant conversion'},{icon:'🔒',title:'Private',desc:'No cloud upload'}],
    faq:[{q:'How to scan to PDF?',a:'Upload images from your camera or gallery and convert them to PDF.'}],
    related:['jpg-to-pdf','compress-pdf','ocr-pdf','merge-pdf'] },

  // === OPTIMIZE PDF ===
  { id:'compress-pdf', name:'Compress PDF', icon:'fas fa-compress-arrows-alt', iconBg:'icon-bg-green', category:'optimize', badge:'hot',
    desc:'Reduce PDF file size while maintaining quality.',
    keywords:'compress pdf, reduce pdf size, shrink pdf, pdf compressor',
    metaDesc:'Compress PDF files online for free. Reduce PDF file size up to 90% without losing quality. Fast & secure — Hi Fi PDF Tool Kit.',
    intro:'Compress your PDF files to reduce file size significantly. Choose auto compression or set a custom target size.',
    steps:['Upload your PDF file','Choose compression level','Click Compress','Download smaller PDF'],
    benefits:[{icon:'📉',title:'Up to 90% Smaller',desc:'Powerful compression'},{icon:'✨',title:'Quality Preserved',desc:'Smart algorithms'},{icon:'⚡',title:'Super Fast',desc:'Instant compression'},{icon:'🔒',title:'100% Secure',desc:'Browser-based processing'}],
    faq:[{q:'How to compress a PDF?',a:'Upload your PDF, select compression level, and download the compressed file.'},{q:'Will compression reduce quality?',a:'Our smart compression minimizes quality loss while maximizing size reduction.'},{q:'What is the maximum file size?',a:'You can compress PDFs up to 100MB for free.'}],
    related:['resize-pdf','compress-50kb','compress-100kb','compress-200kb'] },

  { id:'resize-pdf', name:'Resize PDF', icon:'fas fa-expand-arrows-alt', iconBg:'icon-bg-green', category:'optimize',
    desc:'Resize PDF to exact file size in KB or MB.',
    keywords:'resize pdf, pdf to specific size, reduce pdf to exact size',
    metaDesc:'Resize PDF to exact KB/MB size online free. Set precise file size targets — Hi Fi PDF Tool Kit.',
    intro:'Resize your PDF to an exact target size. Enter the desired size in KB or MB and get precise results.',
    steps:['Upload your PDF','Enter target size (KB/MB)','Click Resize','Download resized PDF'],
    benefits:[{icon:'🎯',title:'Exact Size',desc:'Hit your target precisely'},{icon:'📋',title:'Govt Ready',desc:'Meet form requirements'},{icon:'⚡',title:'Fast',desc:'Quick processing'},{icon:'🔒',title:'Secure',desc:'No server upload'}],
    faq:[{q:'How to resize PDF to exact size?',a:'Upload PDF, enter target size in KB or MB, and click Resize.'}],
    related:['compress-pdf','compress-50kb','compress-100kb','compress-200kb'] },

  { id:'compress-50kb', name:'PDF to 50KB', icon:'fas fa-weight-hanging', iconBg:'icon-bg-green', category:'optimize', badge:'hot',
    desc:'Compress PDF to exactly 50KB for govt forms.',
    keywords:'compress pdf to 50kb, reduce pdf to 50kb, pdf 50kb',
    metaDesc:'Compress PDF to 50KB online free. Perfect for government forms & applications — Hi Fi PDF Tool Kit.',
    intro:'Compress your PDF to exactly 50KB. Perfect for government job applications and online forms that require specific file sizes.',
    steps:['Upload your PDF','Auto-targets 50KB','Click Compress','Download 50KB PDF'],
    benefits:[{icon:'🎯',title:'Exact 50KB',desc:'Precise size targeting'},{icon:'📋',title:'Govt Forms Ready',desc:'Meet all requirements'},{icon:'⚡',title:'One Click',desc:'No settings needed'},{icon:'🔒',title:'Secure',desc:'Private processing'}],
    faq:[{q:'Why 50KB?',a:'Many government forms and applications require PDF uploads under 50KB.'},{q:'Will quality be affected?',a:'We optimize to maintain the best quality possible at 50KB.'}],
    related:['compress-100kb','compress-200kb','compress-pdf','resize-pdf'], targetSize:50 },

  { id:'compress-100kb', name:'PDF to 100KB', icon:'fas fa-weight-hanging', iconBg:'icon-bg-green', category:'optimize', badge:'hot',
    desc:'Compress PDF to exactly 100KB.',
    keywords:'compress pdf to 100kb, reduce pdf to 100kb',
    metaDesc:'Compress PDF to 100KB online free. Fast & accurate compression — Hi Fi PDF Tool Kit.',
    intro:'Compress your PDF to exactly 100KB. Ideal for email attachments and form submissions.',
    steps:['Upload your PDF','Auto-targets 100KB','Click Compress','Download 100KB PDF'],
    benefits:[{icon:'🎯',title:'Exact 100KB',desc:'Precise targeting'},{icon:'📧',title:'Email Ready',desc:'Perfect for attachments'},{icon:'⚡',title:'Instant',desc:'Fast processing'},{icon:'🔒',title:'Secure',desc:'Browser-based'}],
    faq:[{q:'How to compress PDF to 100KB?',a:'Just upload your PDF and it auto-compresses to 100KB.'}],
    related:['compress-50kb','compress-200kb','compress-pdf','resize-pdf'], targetSize:100 },

  { id:'compress-200kb', name:'PDF to 200KB', icon:'fas fa-weight-hanging', iconBg:'icon-bg-green', category:'optimize',
    desc:'Compress PDF to exactly 200KB.',
    keywords:'compress pdf to 200kb, reduce pdf to 200kb',
    metaDesc:'Compress PDF to 200KB online free — Hi Fi PDF Tool Kit.',
    intro:'Compress your PDF to exactly 200KB.',
    steps:['Upload your PDF','Auto-targets 200KB','Click Compress','Download 200KB PDF'],
    benefits:[{icon:'🎯',title:'Exact 200KB',desc:'Precise targeting'},{icon:'⚡',title:'Fast',desc:'Instant results'},{icon:'🔒',title:'Secure',desc:'Private'},{icon:'✨',title:'Quality',desc:'Best possible quality'}],
    faq:[{q:'Why 200KB?',a:'Common size limit for many online application portals.'}],
    related:['compress-100kb','compress-500kb','compress-pdf','resize-pdf'], targetSize:200 },

  { id:'compress-500kb', name:'PDF to 500KB', icon:'fas fa-weight-hanging', iconBg:'icon-bg-green', category:'optimize',
    desc:'Compress PDF to exactly 500KB.',
    keywords:'compress pdf to 500kb',
    metaDesc:'Compress PDF to 500KB online free — Hi Fi PDF Tool Kit.',
    intro:'Compress your PDF to exactly 500KB for document submissions.',
    steps:['Upload your PDF','Auto-targets 500KB','Click Compress','Download 500KB PDF'],
    benefits:[{icon:'🎯',title:'Exact 500KB',desc:'Precise'},{icon:'⚡',title:'Fast',desc:'Quick'},{icon:'🔒',title:'Secure',desc:'Private'},{icon:'✨',title:'Quality',desc:'Maintained'}],
    faq:[{q:'When do I need 500KB?',a:'Many portals limit uploads to 500KB.'}],
    related:['compress-200kb','compress-1mb','compress-pdf','resize-pdf'], targetSize:500 },

  { id:'compress-1mb', name:'PDF to 1MB', icon:'fas fa-weight-hanging', iconBg:'icon-bg-green', category:'optimize',
    desc:'Compress PDF to exactly 1MB.',
    keywords:'compress pdf to 1mb, resize pdf to 1mb',
    metaDesc:'Compress PDF to 1MB online free — Hi Fi PDF Tool Kit.',
    intro:'Compress your PDF to exactly 1MB.',
    steps:['Upload your PDF','Auto-targets 1MB','Click Compress','Download 1MB PDF'],
    benefits:[{icon:'🎯',title:'Exact 1MB',desc:'Precise'},{icon:'⚡',title:'Fast',desc:'Quick'},{icon:'🔒',title:'Secure',desc:'Private'},{icon:'✨',title:'Quality',desc:'Maintained'}],
    faq:[{q:'Why compress to 1MB?',a:'Email attachments often have a 1MB limit.'}],
    related:['compress-500kb','compress-2mb','compress-pdf','resize-pdf'], targetSize:1024 },

  { id:'compress-2mb', name:'PDF to 2MB', icon:'fas fa-weight-hanging', iconBg:'icon-bg-green', category:'optimize',
    desc:'Compress PDF to exactly 2MB.',
    keywords:'compress pdf to 2mb',
    metaDesc:'Compress PDF to 2MB online free — Hi Fi PDF Tool Kit.',
    intro:'Compress your PDF to exactly 2MB for larger document submissions.',
    steps:['Upload your PDF','Auto-targets 2MB','Click Compress','Download 2MB PDF'],
    benefits:[{icon:'🎯',title:'Exact 2MB',desc:'Precise'},{icon:'⚡',title:'Fast',desc:'Quick'},{icon:'🔒',title:'Secure',desc:'Private'},{icon:'✨',title:'Quality',desc:'High'}],
    faq:[],
    related:['compress-1mb','compress-pdf','resize-pdf','merge-pdf'], targetSize:2048 },

  { id:'increase-pdf-size', name:'Increase PDF Size', icon:'fas fa-expand', iconBg:'icon-bg-green', category:'optimize',
    desc:'Increase PDF file size to meet minimum requirements.',
    keywords:'increase pdf size, make pdf bigger, enlarge pdf file size',
    metaDesc:'Increase PDF file size online free. Meet minimum file size requirements — Hi Fi PDF Tool Kit.',
    intro:'Need to increase your PDF file size? Add padding to meet minimum size requirements for uploads.',
    steps:['Upload your PDF','Set target minimum size','Click Increase','Download enlarged PDF'],
    benefits:[{icon:'📈',title:'Size Up',desc:'Meet minimums'},{icon:'📋',title:'Form Ready',desc:'Pass size checks'},{icon:'⚡',title:'Fast',desc:'Instant'},{icon:'🔒',title:'Secure',desc:'Private'}],
    faq:[{q:'Why increase PDF size?',a:'Some forms require a minimum file size for uploads.'}],
    related:['compress-pdf','resize-pdf','repair-pdf','merge-pdf'] },

  { id:'repair-pdf', name:'Repair PDF', icon:'fas fa-wrench', iconBg:'icon-bg-green', category:'optimize',
    desc:'Fix corrupted or damaged PDF files.',
    keywords:'repair pdf, fix pdf, recover corrupted pdf',
    metaDesc:'Repair corrupted PDF files online free. Fix damaged PDFs — Hi Fi PDF Tool Kit.',
    intro:'Repair corrupted or damaged PDF files. Our tool attempts to fix common PDF issues automatically.',
    steps:['Upload corrupted PDF','Auto-detect issues','Click Repair','Download fixed PDF'],
    benefits:[{icon:'🔧',title:'Auto Fix',desc:'Smart repair'},{icon:'💾',title:'Data Recovery',desc:'Recover content'},{icon:'⚡',title:'Fast',desc:'Quick scan'},{icon:'🔒',title:'Secure',desc:'Private'}],
    faq:[{q:'Can all PDFs be repaired?',a:'We can fix most common corruption issues, but severely damaged files may not be recoverable.'}],
    related:['compress-pdf','merge-pdf','unlock-pdf','ocr-pdf'] },

  { id:'ocr-pdf', name:'OCR PDF', icon:'fas fa-eye', iconBg:'icon-bg-green', category:'optimize', badge:'pro',
    desc:'Make scanned PDFs searchable with OCR.',
    keywords:'ocr pdf, searchable pdf, text recognition pdf',
    metaDesc:'OCR PDF online free. Make scanned PDFs searchable — Hi Fi PDF Tool Kit.',
    intro:'Convert scanned PDF documents into searchable text using Optical Character Recognition.',
    steps:['Upload scanned PDF','Select language','Click OCR','Download searchable PDF'],
    benefits:[{icon:'🔍',title:'Searchable Text',desc:'Find any word'},{icon:'🌐',title:'Multi-Language',desc:'30+ languages'},{icon:'⚡',title:'Fast OCR',desc:'Quick processing'},{icon:'🔒',title:'Secure',desc:'Private'}],
    faq:[{q:'What is OCR?',a:'Optical Character Recognition converts images of text into actual searchable text.'}],
    related:['scan-to-pdf','compress-pdf','pdf-to-word','edit-pdf'] },

  // === CONVERT TO PDF ===
  { id:'jpg-to-pdf', name:'JPG to PDF', icon:'fas fa-image', iconBg:'icon-bg-blue', category:'convert-to', badge:'hot',
    desc:'Convert JPG/PNG images to PDF.',
    keywords:'jpg to pdf, image to pdf, png to pdf, photo to pdf',
    metaDesc:'Convert JPG to PDF online free. Turn images into PDF documents instantly — Hi Fi PDF Tool Kit.',
    intro:'Convert your JPG, PNG, or other images into professional PDF documents. Upload multiple images to create a multi-page PDF.',
    steps:['Upload JPG/PNG images','Arrange order & settings','Click Convert','Download PDF'],
    benefits:[{icon:'🖼️',title:'All Formats',desc:'JPG, PNG, WebP, GIF'},{icon:'📄',title:'Multi-Page',desc:'Multiple images to one PDF'},{icon:'⚡',title:'Instant',desc:'Fast conversion'},{icon:'🔒',title:'Secure',desc:'Browser-based'}],
    faq:[{q:'How to convert JPG to PDF?',a:'Upload your images, arrange them, and click Convert to get a PDF.'},{q:'Can I convert multiple images?',a:'Yes, upload multiple images to create a multi-page PDF.'}],
    related:['png-to-pdf','scan-to-pdf','compress-pdf','pdf-to-jpg'] },

  { id:'word-to-pdf', name:'Word to PDF', icon:'fas fa-file-word', iconBg:'icon-bg-blue', category:'convert-to',
    desc:'Convert Word documents to PDF.',
    keywords:'word to pdf, docx to pdf, doc to pdf',
    metaDesc:'Convert Word to PDF online free — Hi Fi PDF Tool Kit.',
    intro:'Convert Microsoft Word documents (.doc, .docx) to PDF format.',
    steps:['Upload Word file','Preview conversion','Click Convert','Download PDF'],
    benefits:[{icon:'📝',title:'Word Support',desc:'.doc & .docx'},{icon:'✨',title:'Formatting',desc:'Preserved layout'},{icon:'⚡',title:'Fast',desc:'Quick conversion'},{icon:'🔒',title:'Secure',desc:'Private'}],
    faq:[{q:'Does it preserve formatting?',a:'We maintain most formatting including fonts, images, and tables.'}],
    related:['excel-to-pdf','ppt-to-pdf','jpg-to-pdf','pdf-to-word'] },

  { id:'ppt-to-pdf', name:'PPT to PDF', icon:'fas fa-file-powerpoint', iconBg:'icon-bg-blue', category:'convert-to',
    desc:'Convert PowerPoint to PDF.',
    keywords:'ppt to pdf, powerpoint to pdf, pptx to pdf',
    metaDesc:'Convert PowerPoint to PDF online free — Hi Fi PDF Tool Kit.',
    intro:'Convert your PowerPoint presentations to PDF format.',
    steps:['Upload PPT file','Preview','Click Convert','Download PDF'],
    benefits:[{icon:'📊',title:'PPT Support',desc:'.ppt & .pptx'},{icon:'✨',title:'Layout Kept',desc:'Slides preserved'},{icon:'⚡',title:'Fast',desc:'Quick'},{icon:'🔒',title:'Secure',desc:'Private'}],
    faq:[],
    related:['word-to-pdf','excel-to-pdf','jpg-to-pdf','compress-pdf'] },

  { id:'excel-to-pdf', name:'Excel to PDF', icon:'fas fa-file-excel', iconBg:'icon-bg-blue', category:'convert-to',
    desc:'Convert Excel spreadsheets to PDF.',
    keywords:'excel to pdf, xlsx to pdf, spreadsheet to pdf',
    metaDesc:'Convert Excel to PDF online free — Hi Fi PDF Tool Kit.',
    intro:'Convert Microsoft Excel spreadsheets to PDF documents.',
    steps:['Upload Excel file','Preview','Click Convert','Download PDF'],
    benefits:[{icon:'📊',title:'Excel Support',desc:'.xls & .xlsx'},{icon:'✨',title:'Tables Kept',desc:'Data preserved'},{icon:'⚡',title:'Fast',desc:'Quick'},{icon:'🔒',title:'Secure',desc:'Private'}],
    faq:[],
    related:['word-to-pdf','ppt-to-pdf','jpg-to-pdf','compress-pdf'] },

  { id:'html-to-pdf', name:'HTML to PDF', icon:'fas fa-code', iconBg:'icon-bg-blue', category:'convert-to',
    desc:'Convert web pages to PDF.',
    keywords:'html to pdf, webpage to pdf, url to pdf',
    metaDesc:'Convert HTML to PDF online free — Hi Fi PDF Tool Kit.',
    intro:'Convert HTML content or web pages into PDF documents.',
    steps:['Paste HTML or URL','Preview','Click Convert','Download PDF'],
    benefits:[{icon:'🌐',title:'Web Pages',desc:'Any HTML content'},{icon:'✨',title:'Styled Output',desc:'CSS preserved'},{icon:'⚡',title:'Fast',desc:'Quick'},{icon:'🔒',title:'Secure',desc:'Private'}],
    faq:[],
    related:['jpg-to-pdf','word-to-pdf','compress-pdf','merge-pdf'] },

  // === CONVERT FROM PDF ===
  { id:'pdf-to-jpg', name:'PDF to JPG', icon:'fas fa-file-image', iconBg:'icon-bg-orange', category:'convert-from', badge:'hot',
    desc:'Convert PDF pages to JPG images.',
    keywords:'pdf to jpg, pdf to image, convert pdf to jpg, pdf to png',
    metaDesc:'Convert PDF to JPG online free. Extract images from PDF pages — Hi Fi PDF Tool Kit.',
    intro:'Convert each page of your PDF into high-quality JPG images. Perfect for sharing on social media or presentations.',
    steps:['Upload your PDF','Choose quality & format','Click Convert','Download images'],
    benefits:[{icon:'🖼️',title:'High Quality',desc:'Crystal clear images'},{icon:'📱',title:'Share Ready',desc:'For social media'},{icon:'⚡',title:'Fast',desc:'Instant conversion'},{icon:'📦',title:'Batch Download',desc:'All pages at once'}],
    faq:[{q:'What quality are the images?',a:'We export at high resolution (300 DPI) by default.'},{q:'Can I convert specific pages?',a:'Yes, select which pages to convert.'}],
    related:['pdf-to-word','pdf-to-excel','jpg-to-pdf','compress-pdf'] },

  { id:'pdf-to-word', name:'PDF to Word', icon:'fas fa-file-word', iconBg:'icon-bg-orange', category:'convert-from',
    desc:'Convert PDF to editable Word documents.',
    keywords:'pdf to word, pdf to docx, convert pdf to word',
    metaDesc:'Convert PDF to Word online free — Hi Fi PDF Tool Kit.',
    intro:'Convert your PDF files to editable Microsoft Word documents.',
    steps:['Upload PDF','Click Convert','Download Word file'],
    benefits:[{icon:'📝',title:'Editable Output',desc:'Edit in Word'},{icon:'✨',title:'Formatting',desc:'Layout maintained'},{icon:'⚡',title:'Fast',desc:'Quick conversion'},{icon:'🔒',title:'Secure',desc:'Private'}],
    faq:[{q:'Is the text editable?',a:'Yes, converted text is fully editable in Microsoft Word.'}],
    related:['pdf-to-excel','pdf-to-jpg','word-to-pdf','compress-pdf'] },

  { id:'pdf-to-ppt', name:'PDF to PPT', icon:'fas fa-file-powerpoint', iconBg:'icon-bg-orange', category:'convert-from',
    desc:'Convert PDF to PowerPoint slides.',
    keywords:'pdf to ppt, pdf to powerpoint',
    metaDesc:'Convert PDF to PowerPoint online free — Hi Fi PDF Tool Kit.',
    intro:'Convert PDF documents into editable PowerPoint presentations.',
    steps:['Upload PDF','Click Convert','Download PPT'],
    benefits:[{icon:'📊',title:'Slide Output',desc:'Editable slides'},{icon:'⚡',title:'Fast',desc:'Quick'},{icon:'🔒',title:'Secure',desc:'Private'},{icon:'✨',title:'Quality',desc:'Clean slides'}],
    faq:[],
    related:['pdf-to-word','pdf-to-excel','ppt-to-pdf','pdf-to-jpg'] },

  { id:'pdf-to-excel', name:'PDF to Excel', icon:'fas fa-file-excel', iconBg:'icon-bg-orange', category:'convert-from',
    desc:'Convert PDF tables to Excel spreadsheets.',
    keywords:'pdf to excel, pdf to xlsx, extract table from pdf',
    metaDesc:'Convert PDF to Excel online free — Hi Fi PDF Tool Kit.',
    intro:'Extract tables from PDF and convert to editable Excel spreadsheets.',
    steps:['Upload PDF','Auto-detect tables','Click Convert','Download Excel'],
    benefits:[{icon:'📊',title:'Table Detection',desc:'Smart extraction'},{icon:'⚡',title:'Fast',desc:'Quick'},{icon:'🔒',title:'Secure',desc:'Private'},{icon:'✨',title:'Accurate',desc:'Clean data'}],
    faq:[],
    related:['pdf-to-word','pdf-to-jpg','excel-to-pdf','compress-pdf'] },

  { id:'pdf-to-pdfa', name:'PDF to PDF/A', icon:'fas fa-archive', iconBg:'icon-bg-orange', category:'convert-from',
    desc:'Convert PDF to archival PDF/A format.',
    keywords:'pdf to pdfa, pdf archival format',
    metaDesc:'Convert PDF to PDF/A online free — Hi Fi PDF Tool Kit.',
    intro:'Convert your PDFs to PDF/A format for long-term archiving and compliance.',
    steps:['Upload PDF','Select PDF/A version','Click Convert','Download PDF/A'],
    benefits:[{icon:'📦',title:'Archival',desc:'Long-term storage'},{icon:'✅',title:'Compliant',desc:'ISO standard'},{icon:'⚡',title:'Fast',desc:'Quick'},{icon:'🔒',title:'Secure',desc:'Private'}],
    faq:[],
    related:['compress-pdf','merge-pdf','protect-pdf','repair-pdf'] },

  // === EDIT PDF ===
  { id:'rotate-pdf', name:'Rotate PDF', icon:'fas fa-sync-alt', iconBg:'icon-bg-pink', category:'edit',
    desc:'Rotate PDF pages to any angle.',
    keywords:'rotate pdf, turn pdf pages, flip pdf',
    metaDesc:'Rotate PDF pages online free. Turn pages 90°, 180° or 270° — Hi Fi PDF Tool Kit.',
    intro:'Rotate individual pages or all pages in your PDF. Fix upside-down or sideways scans easily.',
    steps:['Upload your PDF','Select rotation angle','Choose pages','Download rotated PDF'],
    benefits:[{icon:'🔄',title:'Any Angle',desc:'90°, 180°, 270°'},{icon:'📄',title:'Per Page',desc:'Rotate individual pages'},{icon:'⚡',title:'Fast',desc:'Instant'},{icon:'🔒',title:'Secure',desc:'Private'}],
    faq:[{q:'Can I rotate specific pages?',a:'Yes, select individual pages or rotate all at once.'}],
    related:['crop-pdf','add-page-numbers','rearrange-pages','compress-pdf'] },

  { id:'add-page-numbers', name:'Add Page Numbers', icon:'fas fa-list-ol', iconBg:'icon-bg-pink', category:'edit',
    desc:'Add page numbers to your PDF.',
    keywords:'add page numbers to pdf, page numbering pdf',
    metaDesc:'Add page numbers to PDF online free — Hi Fi PDF Tool Kit.',
    intro:'Add professional page numbers to your PDF documents. Choose position, format, and style.',
    steps:['Upload PDF','Choose position & format','Click Add','Download numbered PDF'],
    benefits:[{icon:'#️⃣',title:'Custom Format',desc:'Multiple styles'},{icon:'📐',title:'Position Control',desc:'Top/Bottom/Corner'},{icon:'⚡',title:'Fast',desc:'Instant'},{icon:'🔒',title:'Secure',desc:'Private'}],
    faq:[],
    related:['add-watermark','rotate-pdf','merge-pdf','compress-pdf'] },

  { id:'add-watermark', name:'Add Watermark', icon:'fas fa-copyright', iconBg:'icon-bg-pink', category:'edit',
    desc:'Add text or image watermark to PDF.',
    keywords:'add watermark to pdf, pdf watermark, stamp pdf',
    metaDesc:'Add watermark to PDF online free — Hi Fi PDF Tool Kit.',
    intro:'Add professional text or image watermarks to protect your PDF documents.',
    steps:['Upload PDF','Enter watermark text/image','Customize appearance','Download watermarked PDF'],
    benefits:[{icon:'🏷️',title:'Text & Image',desc:'Both supported'},{icon:'🎨',title:'Customizable',desc:'Font, size, opacity'},{icon:'⚡',title:'Fast',desc:'Instant'},{icon:'🔒',title:'Secure',desc:'Private'}],
    faq:[],
    related:['protect-pdf','add-page-numbers','sign-pdf','compress-pdf'] },

  { id:'crop-pdf', name:'Crop PDF', icon:'fas fa-crop-alt', iconBg:'icon-bg-pink', category:'edit',
    desc:'Crop PDF pages to remove margins.',
    keywords:'crop pdf, trim pdf margins, cut pdf edges',
    metaDesc:'Crop PDF pages online free. Remove margins and trim edges — Hi Fi PDF Tool Kit.',
    intro:'Crop your PDF pages to remove unwanted margins, borders, or whitespace.',
    steps:['Upload PDF','Set crop area','Apply to pages','Download cropped PDF'],
    benefits:[{icon:'✂️',title:'Precise Crop',desc:'Pixel-perfect'},{icon:'📄',title:'Per Page',desc:'Crop individually'},{icon:'⚡',title:'Fast',desc:'Instant'},{icon:'🔒',title:'Secure',desc:'Private'}],
    faq:[],
    related:['crop-single-page','rotate-pdf','compress-pdf','split-pdf'] },

  { id:'crop-single-page', name:'Crop Single Page', icon:'fas fa-expand', iconBg:'icon-bg-pink', category:'edit',
    desc:'Crop a specific page in your PDF.',
    keywords:'crop single page pdf, crop one page',
    metaDesc:'Crop single PDF page online free — Hi Fi PDF Tool Kit.',
    intro:'Crop a specific page in your PDF without affecting other pages.',
    steps:['Upload PDF','Select page','Set crop area','Download'],
    benefits:[{icon:'🎯',title:'Single Page',desc:'Targeted crop'},{icon:'✂️',title:'Precise',desc:'Exact area'},{icon:'⚡',title:'Fast',desc:'Instant'},{icon:'🔒',title:'Secure',desc:'Private'}],
    faq:[],
    related:['crop-pdf','rotate-pdf','extract-pages','remove-pages'] },

  { id:'edit-pdf', name:'Edit PDF', icon:'fas fa-pen', iconBg:'icon-bg-pink', category:'edit', badge:'pro',
    desc:'Edit text and images in your PDF.',
    keywords:'edit pdf, modify pdf text, change pdf content',
    metaDesc:'Edit PDF online free. Modify text and images in your PDF — Hi Fi PDF Tool Kit.',
    intro:'Edit text, add images, and modify content directly in your PDF document.',
    steps:['Upload PDF','Click to edit text/images','Make changes','Download edited PDF'],
    benefits:[{icon:'✏️',title:'Edit Text',desc:'Modify content'},{icon:'🖼️',title:'Add Images',desc:'Insert graphics'},{icon:'⚡',title:'Fast',desc:'Real-time editing'},{icon:'🔒',title:'Secure',desc:'Private'}],
    faq:[],
    related:['add-watermark','sign-pdf','add-page-numbers','compress-pdf'] },

  { id:'sign-pdf', name:'Sign PDF', icon:'fas fa-signature', iconBg:'icon-bg-pink', category:'edit',
    desc:'Add digital signature to your PDF.',
    keywords:'sign pdf, add signature to pdf, e-sign pdf',
    metaDesc:'Sign PDF online free. Add your signature to PDF documents — Hi Fi PDF Tool Kit.',
    intro:'Add your handwritten signature or typed signature to PDF documents.',
    steps:['Upload PDF','Draw or type signature','Place on document','Download signed PDF'],
    benefits:[{icon:'✍️',title:'Draw Signature',desc:'Handwritten style'},{icon:'⌨️',title:'Type Signature',desc:'Professional fonts'},{icon:'⚡',title:'Fast',desc:'Instant'},{icon:'🔒',title:'Secure',desc:'Private'}],
    faq:[],
    related:['edit-pdf','add-watermark','protect-pdf','compress-pdf'] },

  // === SECURITY ===
  { id:'unlock-pdf', name:'Unlock PDF', icon:'fas fa-lock-open', iconBg:'icon-bg-red', category:'security',
    desc:'Remove password protection from PDF.',
    keywords:'unlock pdf, remove pdf password, unprotect pdf',
    metaDesc:'Unlock PDF online free. Remove password protection — Hi Fi PDF Tool Kit.',
    intro:'Remove password protection from your PDF files. You must know the password to unlock.',
    steps:['Upload locked PDF','Enter password','Click Unlock','Download unlocked PDF'],
    benefits:[{icon:'🔓',title:'Instant Unlock',desc:'Remove restrictions'},{icon:'⚡',title:'Fast',desc:'Quick processing'},{icon:'🔒',title:'Secure',desc:'We never store passwords'},{icon:'📄',title:'Full Access',desc:'Edit & print freely'}],
    faq:[{q:'Can you unlock without password?',a:'You need to provide the correct password to unlock the PDF.'}],
    related:['protect-pdf','compress-pdf','merge-pdf','edit-pdf'] },

  { id:'protect-pdf', name:'Protect PDF', icon:'fas fa-lock', iconBg:'icon-bg-red', category:'security',
    desc:'Add password protection to PDF.',
    keywords:'protect pdf, password pdf, encrypt pdf, secure pdf',
    metaDesc:'Protect PDF with password online free — Hi Fi PDF Tool Kit.',
    intro:'Add password protection to your PDF files to prevent unauthorized access.',
    steps:['Upload PDF','Set password','Choose permissions','Download protected PDF'],
    benefits:[{icon:'🔐',title:'Strong Encryption',desc:'AES-256 encryption'},{icon:'⚙️',title:'Permissions',desc:'Control print/edit/copy'},{icon:'⚡',title:'Fast',desc:'Instant'},{icon:'🔒',title:'Secure',desc:'Private processing'}],
    faq:[],
    related:['unlock-pdf','add-watermark','redact-pdf','sign-pdf'] },

  { id:'redact-pdf', name:'Redact PDF', icon:'fas fa-eraser', iconBg:'icon-bg-red', category:'security', badge:'pro',
    desc:'Permanently remove sensitive information from PDF.',
    keywords:'redact pdf, black out pdf text, censor pdf',
    metaDesc:'Redact PDF online free. Remove sensitive information — Hi Fi PDF Tool Kit.',
    intro:'Permanently redact sensitive information from your PDF documents.',
    steps:['Upload PDF','Select text to redact','Apply redaction','Download redacted PDF'],
    benefits:[{icon:'🖤',title:'Permanent',desc:'Cannot be undone'},{icon:'🔒',title:'Secure',desc:'Data removed, not hidden'},{icon:'⚡',title:'Fast',desc:'Quick'},{icon:'📋',title:'Compliant',desc:'GDPR ready'}],
    faq:[],
    related:['protect-pdf','unlock-pdf','edit-pdf','compress-pdf'] },

  { id:'compare-pdf', name:'Compare PDF', icon:'fas fa-columns', iconBg:'icon-bg-red', category:'security',
    desc:'Compare two PDFs side by side.',
    keywords:'compare pdf, pdf diff, difference between pdfs',
    metaDesc:'Compare PDFs online free. Find differences between two PDF files — Hi Fi PDF Tool Kit.',
    intro:'Compare two PDF documents side by side to find differences.',
    steps:['Upload first PDF','Upload second PDF','Click Compare','View differences'],
    benefits:[{icon:'👁️',title:'Visual Diff',desc:'Side by side'},{icon:'🔍',title:'Detailed',desc:'Highlight changes'},{icon:'⚡',title:'Fast',desc:'Quick comparison'},{icon:'🔒',title:'Secure',desc:'Private'}],
    faq:[],
    related:['merge-pdf','split-pdf','edit-pdf','compress-pdf'] },

  // === AI TOOLS ===
  { id:'ai-summarize', name:'AI Summarize PDF', icon:'fas fa-brain', iconBg:'icon-bg-indigo', category:'ai', badge:'pro',
    desc:'AI-powered PDF summarization.',
    keywords:'ai pdf summary, summarize pdf, pdf summary tool',
    metaDesc:'AI PDF Summarizer — Get instant summaries of your PDF documents — Hi Fi PDF Tool Kit.',
    intro:'Use AI to instantly summarize your PDF documents. Get key points, highlights, and a concise overview.',
    steps:['Upload PDF','AI analyzes content','Review summary','Copy or download'],
    benefits:[{icon:'🤖',title:'AI Powered',desc:'Smart analysis'},{icon:'📝',title:'Key Points',desc:'Extract highlights'},{icon:'⚡',title:'Instant',desc:'Quick results'},{icon:'🌐',title:'Any Language',desc:'Multi-language support'}],
    faq:[{q:'How does AI summarization work?',a:'Our AI reads your PDF content and generates a concise summary highlighting key points.'}],
    related:['ai-translate','ocr-pdf','edit-pdf','compress-pdf'], isPremium:true },

  { id:'ai-translate', name:'AI Translate PDF', icon:'fas fa-language', iconBg:'icon-bg-indigo', category:'ai', badge:'pro',
    desc:'AI-powered PDF translation.',
    keywords:'translate pdf, pdf translator, convert pdf language',
    metaDesc:'AI PDF Translator — Translate PDF documents to any language — Hi Fi PDF Tool Kit.',
    intro:'Translate your PDF documents to any language using advanced AI translation.',
    steps:['Upload PDF','Select target language','AI translates','Download translated PDF'],
    benefits:[{icon:'🌍',title:'100+ Languages',desc:'Global coverage'},{icon:'🤖',title:'AI Quality',desc:'Natural translations'},{icon:'⚡',title:'Fast',desc:'Quick translation'},{icon:'📄',title:'Layout Kept',desc:'Formatting preserved'}],
    faq:[],
    related:['ai-summarize','ocr-pdf','pdf-to-word','edit-pdf'], isPremium:true },

  // === VIRAL TOOLS ===
  { id:'meesho-label', name:'Meesho Label Cropper', icon:'fas fa-tag', iconBg:'icon-bg-yellow', category:'viral', badge:'hot',
    desc:'Crop Meesho shipping labels from PDF.',
    keywords:'meesho label crop, meesho shipping label pdf, meesho label cutter',
    metaDesc:'Meesho Label Cropper — Crop shipping labels from Meesho PDF free — Hi Fi PDF Tool Kit.',
    intro:'Instantly crop and extract shipping labels from Meesho order PDFs. Save paper and print only the labels you need.',
    steps:['Upload Meesho label PDF','Auto-detect labels','Crop labels','Download cropped labels'],
    benefits:[{icon:'🏷️',title:'Auto Detect',desc:'Smart label detection'},{icon:'🖨️',title:'Save Paper',desc:'Print only labels'},{icon:'⚡',title:'Instant',desc:'Quick cropping'},{icon:'💰',title:'Save Money',desc:'Reduce printing costs'}],
    faq:[{q:'How does Meesho label cropping work?',a:'Upload your Meesho shipping PDF and our tool automatically detects and crops the labels.'},{q:'Does it work with all Meesho labels?',a:'Yes, it works with all standard Meesho shipping label formats.'}],
    related:['flipkart-label','amazon-label','crop-pdf','compress-pdf'] },

  { id:'flipkart-label', name:'Flipkart Label Cropper', icon:'fas fa-tag', iconBg:'icon-bg-yellow', category:'viral', badge:'hot',
    desc:'Crop Flipkart shipping labels from PDF.',
    keywords:'flipkart label crop, flipkart shipping label, flipkart label cutter',
    metaDesc:'Flipkart Label Cropper — Crop shipping labels from Flipkart PDF free — Hi Fi PDF Tool Kit.',
    intro:'Crop and extract shipping labels from Flipkart order PDFs. Print only the labels, save paper and ink.',
    steps:['Upload Flipkart label PDF','Auto-detect labels','Crop labels','Download cropped labels'],
    benefits:[{icon:'🏷️',title:'Auto Detect',desc:'Smart detection'},{icon:'🖨️',title:'Save Paper',desc:'Labels only'},{icon:'⚡',title:'Instant',desc:'Quick'},{icon:'💰',title:'Save Money',desc:'Less ink'}],
    faq:[],
    related:['meesho-label','amazon-label','crop-pdf','compress-pdf'] },

  { id:'amazon-label', name:'Amazon Label Tool', icon:'fas fa-tag', iconBg:'icon-bg-yellow', category:'viral',
    desc:'Crop Amazon shipping labels from PDF.',
    keywords:'amazon label crop, amazon shipping label, amazon fba label',
    metaDesc:'Amazon Label Tool — Crop shipping labels from Amazon PDF free — Hi Fi PDF Tool Kit.',
    intro:'Extract and crop shipping labels from Amazon order PDFs for efficient printing.',
    steps:['Upload Amazon label PDF','Auto-detect labels','Crop labels','Download'],
    benefits:[{icon:'🏷️',title:'Auto Detect',desc:'Smart detection'},{icon:'🖨️',title:'Save Paper',desc:'Labels only'},{icon:'⚡',title:'Fast',desc:'Quick'},{icon:'📦',title:'FBA Ready',desc:'FBA label support'}],
    faq:[],
    related:['meesho-label','flipkart-label','crop-pdf','compress-pdf'] },

  { id:'whatsapp-compress', name:'WhatsApp PDF Compress', icon:'fab fa-whatsapp', iconBg:'icon-bg-green', category:'viral', badge:'hot',
    desc:'Compress PDF for WhatsApp sharing.',
    keywords:'whatsapp pdf compress, compress pdf for whatsapp, send large pdf whatsapp',
    metaDesc:'Compress PDF for WhatsApp free. Reduce PDF size to send via WhatsApp — Hi Fi PDF Tool Kit.',
    intro:'Compress your PDF to the perfect size for sharing on WhatsApp. One-click compression to under 100KB.',
    steps:['Upload PDF','Auto-compress for WhatsApp','Click Compress','Share on WhatsApp'],
    benefits:[{icon:'💬',title:'WhatsApp Ready',desc:'Perfect size for sharing'},{icon:'⚡',title:'One Click',desc:'Instant compression'},{icon:'📱',title:'Mobile Friendly',desc:'Optimized for phones'},{icon:'🔒',title:'Secure',desc:'Private processing'}],
    faq:[{q:'What size limit does WhatsApp have?',a:'WhatsApp supports PDFs up to 100MB, but smaller files share faster.'}],
    related:['compress-pdf','compress-100kb','compress-50kb','resize-pdf'], targetSize:100 },

  { id:'resume-optimizer', name:'Resume Optimizer', icon:'fas fa-file-alt', iconBg:'icon-bg-yellow', category:'viral',
    desc:'Optimize your resume PDF for job applications.',
    keywords:'resume pdf optimizer, optimize resume pdf, ats friendly resume',
    metaDesc:'Resume PDF Optimizer — Optimize your resume for job applications free — Hi Fi PDF Tool Kit.',
    intro:'Optimize your resume PDF for job applications. Compress to the right size and ensure ATS compatibility.',
    steps:['Upload resume PDF','Choose optimization','Apply settings','Download optimized resume'],
    benefits:[{icon:'📄',title:'ATS Friendly',desc:'Pass applicant systems'},{icon:'📏',title:'Right Size',desc:'Under 1MB'},{icon:'⚡',title:'Fast',desc:'Instant optimization'},{icon:'🎯',title:'Job Ready',desc:'Professional output'}],
    faq:[],
    related:['compress-pdf','compress-1mb','edit-pdf','sign-pdf'] },

  { id:'govt-photo-resize', name:'Photo Resize (Govt)', icon:'fas fa-id-card', iconBg:'icon-bg-yellow', category:'viral', badge:'hot',
    desc:'Resize photos for government forms (passport, visa, ID).',
    keywords:'resize photo for govt form, passport photo size, photo resize kb',
    metaDesc:'Resize photo for government forms free. Passport size photo, ID photo — Hi Fi PDF Tool Kit.',
    intro:'Resize your photos to exact specifications for government forms — passport, visa, Aadhaar, PAN card applications.',
    steps:['Upload photo','Select form type','Auto-resize','Download resized photo'],
    benefits:[{icon:'📐',title:'Exact Size',desc:'3.5x4.5cm, 2x2in'},{icon:'📋',title:'All Forms',desc:'Passport, Visa, ID'},{icon:'⚡',title:'Instant',desc:'Auto-resize'},{icon:'🎯',title:'Precise',desc:'KB-accurate'}],
    faq:[{q:'What sizes are supported?',a:'Passport (3.5x4.5cm), Visa (2x2in), Aadhaar, PAN, and custom sizes.'}],
    related:['govt-signature-resize','compress-50kb','jpg-to-pdf','compress-pdf'] },

  { id:'govt-signature-resize', name:'Signature Resize', icon:'fas fa-pen-nib', iconBg:'icon-bg-yellow', category:'viral',
    desc:'Resize signature image for government forms.',
    keywords:'signature resize for govt form, signature size kb, resize signature',
    metaDesc:'Resize signature for government forms free — Hi Fi PDF Tool Kit.',
    intro:'Resize your signature image to exact specifications for government exam forms and applications.',
    steps:['Upload signature','Select size requirement','Auto-resize','Download'],
    benefits:[{icon:'✍️',title:'Exact Size',desc:'10-20KB target'},{icon:'📋',title:'Form Ready',desc:'All govt forms'},{icon:'⚡',title:'Instant',desc:'Auto-resize'},{icon:'🎯',title:'Precise',desc:'Pixel-perfect'}],
    faq:[],
    related:['govt-photo-resize','compress-50kb','jpg-to-pdf','compress-pdf'] },

  // === EXTRAS ===
  { id:'word-count', name:'Word Count', icon:'fas fa-calculator', iconBg:'icon-bg-teal', category:'extras',
    desc:'Count words, characters, and pages in PDF.',
    keywords:'count words in pdf, pdf word counter, pdf statistics',
    metaDesc:'Count words in PDF online free — Hi Fi PDF Tool Kit.',
    intro:'Get detailed word count, character count, and page statistics for your PDF documents.',
    steps:['Upload PDF','Auto-analyze','View statistics','Copy results'],
    benefits:[{icon:'📊',title:'Detailed Stats',desc:'Words, chars, pages'},{icon:'⚡',title:'Instant',desc:'Quick analysis'},{icon:'📋',title:'Copy Results',desc:'Share easily'},{icon:'🔒',title:'Secure',desc:'Private'}],
    faq:[],
    related:['ocr-pdf','compress-pdf','edit-pdf','merge-pdf'] },

  { id:'bulk-process', name:'Bulk Processing', icon:'fas fa-layer-group', iconBg:'icon-bg-teal', category:'extras', badge:'pro',
    desc:'Process multiple PDFs at once.',
    keywords:'bulk pdf processing, batch pdf, multiple pdf',
    metaDesc:'Bulk PDF processing online — Process multiple PDFs at once — Hi Fi PDF Tool Kit.',
    intro:'Process multiple PDF files simultaneously. Compress, convert, or merge in bulk for maximum efficiency.',
    steps:['Upload multiple PDFs','Select operation','Process all','Download results'],
    benefits:[{icon:'📦',title:'Batch Mode',desc:'Process many at once'},{icon:'⚡',title:'Fast',desc:'Parallel processing'},{icon:'💾',title:'Bulk Download',desc:'ZIP download'},{icon:'🔒',title:'Secure',desc:'Private'}],
    faq:[],
    related:['compress-pdf','merge-pdf','jpg-to-pdf','pdf-to-jpg'], isPremium:true },

  { id:'save-presets', name:'Save Presets', icon:'fas fa-sliders-h', iconBg:'icon-bg-teal', category:'extras',
    desc:'Save your favorite tool settings as presets.',
    keywords:'save pdf presets, pdf tool settings',
    metaDesc:'Save PDF tool presets — Quick access to your favorite settings — Hi Fi PDF Tool Kit.',
    intro:'Save your frequently used tool settings as presets for one-click access.',
    steps:['Use any tool','Save current settings','Name your preset','Access anytime'],
    benefits:[{icon:'💾',title:'Quick Access',desc:'One-click presets'},{icon:'⚙️',title:'Custom Settings',desc:'Your preferences'},{icon:'🔄',title:'Reusable',desc:'Use again & again'},{icon:'📱',title:'Synced',desc:'Saved locally'}],
    faq:[],
    related:['compress-pdf','resize-pdf','bulk-process','merge-pdf'] },

  { id:'recent-history', name:'Recent History', icon:'fas fa-history', iconBg:'icon-bg-teal', category:'extras',
    desc:'View and repeat recent tool actions.',
    keywords:'pdf tool history, recent pdf actions',
    metaDesc:'PDF tool history — Repeat recent actions quickly — Hi Fi PDF Tool Kit.',
    intro:'Access your recent tool usage history and repeat actions with one click.',
    steps:['Open Recent History','Browse past actions','Click to repeat','Process instantly'],
    benefits:[{icon:'🕐',title:'Quick Repeat',desc:'One-click redo'},{icon:'📋',title:'Full History',desc:'All recent actions'},{icon:'⚡',title:'Fast',desc:'Instant access'},{icon:'🔒',title:'Local Only',desc:'Stored on device'}],
    faq:[],
    related:['save-presets','compress-pdf','merge-pdf','bulk-process'] }
];

// Programmatic SEO size variants
const SIZE_VARIANTS = [
  { size: 10, unit: 'kb', label: '10KB' },
  { size: 20, unit: 'kb', label: '20KB' },
  { size: 30, unit: 'kb', label: '30KB' },
  { size: 50, unit: 'kb', label: '50KB' },
  { size: 100, unit: 'kb', label: '100KB' },
  { size: 150, unit: 'kb', label: '150KB' },
  { size: 200, unit: 'kb', label: '200KB' },
  { size: 300, unit: 'kb', label: '300KB' },
  { size: 400, unit: 'kb', label: '400KB' },
  { size: 500, unit: 'kb', label: '500KB' },
  { size: 1, unit: 'mb', label: '1MB' },
  { size: 2, unit: 'mb', label: '2MB' },
  { size: 3, unit: 'mb', label: '3MB' },
  { size: 5, unit: 'mb', label: '5MB' },
  { size: 10, unit: 'mb', label: '10MB' }
];

function getToolById(id) {
  return ALL_TOOLS.find(t => t.id === id);
}

function getToolsByCategory(catId) {
  if (catId === 'all') return ALL_TOOLS;
  return ALL_TOOLS.filter(t => t.category === catId);
}

function searchTools(query) {
  const q = query.toLowerCase().trim();
  if (!q) return ALL_TOOLS;
  return ALL_TOOLS.filter(t =>
    t.name.toLowerCase().includes(q) ||
    t.desc.toLowerCase().includes(q) ||
    (t.keywords && t.keywords.toLowerCase().includes(q))
  );
}

function getRelatedTools(toolId) {
  const tool = getToolById(toolId);
  if (!tool || !tool.related) return [];
  return tool.related.map(id => getToolById(id)).filter(Boolean);
}
